apiVersion: v1
kind: Service
metadata:
  name: apicurio-registry-service
spec:
  type: NodePort
  selector:
    app: apicurio-registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000 # Adjust if you want a different port
